name: pytmd
channels:
  - conda-forge
dependencies:
  - cartopy
  - ipyleaflet
  - ipywidgets
  - jplephem
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - pandas
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - scipy>=1.16.0
  - timescale>=0.0.8
